stages:
  - lint
  - build
  - deploy

.cache: &global_cache
  key: api-sabay-one-cache-key
  paths:
    - node_modules/

# run linting
eslint:
  stage: lint
  image: docker-registry.sabay.com/docker/node:latest
  allow_failure: true
  coverage: /All files\s*\|\s*([\d\.]+)/
  cache:
    <<: *global_cache
  script:
    - npm i
    - npm run lint
  only:
    - merge_requests
  tags:
    - docker

# run build and upload project to registry
docker_build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make build
    - make push
  only:
    - master
    - tags
  tags:
    - container-build

# tag IMAGE:prod from IMAGE:testing
tag_prod:
  stage: deploy
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - make tag-prod
  only:
    - tags
  tags:
    - container-build
  when: manual
