export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testRegex: '(/test/.*|(\\.|/)(test|spec))\\.(js?|ts?)$',
  collectCoverage: true,
  testPathIgnorePatterns: [
    '/dist/',
    '/docker/',
    '/build/',
    '/lib/',
    '/node_modules/',
    '/src/utils/',
    '/src/config/',
    '/src/models/',
    '/src/test/mock/',
  ],
  coverageDirectory: './coverage',
  coveragePathIgnorePatterns: [
    'node_modules',
    '/src/config/',
    '/src/models/',
    '/src/test/mock/',
  ],
  globals: { 'ts-jest': { diagnostics: false } },
  transform: {},
  verbose: true,
  setupFilesAfterEnv: ['./jest.setup.ts'],
  globalSetup: './jest.global.setup.ts',
  globalTeardown: './jest.teardown.ts',
  testTimeout: 30000,
};
