import dotEnv from 'dotenv';

const isUnitTest = ['test', 'ci_test'].includes(process.env.NODE_ENV);
if (isUnitTest) dotEnv.config({ path: './src/test/.test.env' });

const {
  APP_PORT,
  NODE_ENV,
  IMG,
  TAG,

  MONGO_DB_URI,
  MONGO_DB_USERNAME,
  MONGO_DB_PASSWORD,

  JAEGER_HOST,
  JAEGER_SPAN_LOGGING,

  RABBITMQ_HOST,
  RABBITMQ_USER,
  RABBITMQ_PASSWORD,
  RABBITMQ_VHOST,

  REDIS_HOST,
  REDIS_PORT,

  SLACK_APP_TOKEN,
  SLACK_CHANNEL,
  SLACK_API_URL,

  MOVIE_API_TOKEN,
  BOOK_API_TOKEN,

  ROW_LIMIT,
  MAX_LIMIT,
  RETRY_INTERVAL,
  ENABLE_INTROSPECTION,
  DEBUG_MODE,
  MAXIMUM_OBJECT_SIZE,
  CACHED_EXPIRE,

  MOVIE_API_URL,
  BOOK_API_URL,
  PODCAST_API_URL,
  API_USER_PSP_URL,
  PAYMENT_ADDRESS_DOMAIN,
  API_SSN_URL,

  APPLE_BUNDLE_ID,
  APPLE_APP_ID,
  APPLE_ENABLE_ONLINE_CHECK,
  APPLE_TEST,
  MICROSERVICE_JWT_SK,
  ABA_PAY_API_KEY,
  ABA_PAY_MERCHANT_ID,
  ABA_PAY_WAY_URL,

  WING_PAY_API_KEY,
  WING_PAY_WAY_URL,
  WING_PAY_USERNAME,
} = process.env;

const ENV = {
  APP_PORT: APP_PORT || 3000,
  NODE_ENV,
  IMG,
  TAG,

  MONGO_DB_URI,
  MONGO_DB_USERNAME,
  MONGO_DB_PASSWORD,

  JAEGER_HOST,
  JAEGER_SPAN_LOGGING: JAEGER_SPAN_LOGGING === 'true',
  IS_UNIT_TEST: isUnitTest as boolean,

  RABBITMQ_HOST,
  RABBITMQ_USER,
  RABBITMQ_PASSWORD,
  RABBITMQ_VHOST,

  REDIS_HOST,
  REDIS_PORT,

  SLACK_APP_TOKEN,
  SLACK_CHANNEL,
  SLACK_API_URL,

  MOVIE_API_TOKEN,
  BOOK_API_TOKEN,

  ROW_LIMIT: Number(ROW_LIMIT) || 20,
  MAX_LIMIT: Number(MAX_LIMIT) || 100,
  RETRY_INTERVAL: Number(RETRY_INTERVAL) || 3000,
  ENABLE_INTROSPECTION: ENABLE_INTROSPECTION === 'true',
  DEBUG_MODE: Number(DEBUG_MODE) === 1, // 1=ON | 0=OFF
  MAXIMUM_OBJECT_SIZE: Number(MAXIMUM_OBJECT_SIZE) || 1, // 1 = 1MB
  CACHED_EXPIRE,
  MOVIE_API_URL,
  BOOK_API_URL,
  PODCAST_API_URL,
  API_USER_PSP_URL,
  PAYMENT_ADDRESS_DOMAIN,
  API_SSN_URL,

  APPLE_BUNDLE_ID,
  APPLE_APP_ID: Number(APPLE_APP_ID),
  APPLE_ENABLE_ONLINE_CHECK: APPLE_ENABLE_ONLINE_CHECK === 'true',
  APPLE_TEST: APPLE_TEST ? JSON.parse(APPLE_TEST) : true,
  MICROSERVICE_JWT_SK,
  ABA_PAY_API_KEY,
  ABA_PAY_MERCHANT_ID,
  ABA_PAY_WAY_URL,

  WING_PAY_API_KEY,
  WING_PAY_WAY_URL,
  WING_PAY_USERNAME,
};

export default ENV;
